In [14]:
# {tileid:{id:{feature}}}
tileid2oa2features2vals

{'6': {'2116465375039999220': {'work_count': 3586,
   'work_female': 0.464,
   'work_male': 0.536,
   'work_age_11': 0.189,
   'work_age_12': 0.225,
   'work_age_13': 0.204,
   'work_age_14': 0.137,
   'work_age_15': 0.073,
   'work_age_16': 0.09,
   'work_age_10': 0.063,
   'home_count': 6914,
   'home_female': 0.481,
   'home_male': 0.519,
   'home_age_11': 0.207,
   'home_age_12': 0.247,
   'home_age_13': 0.178,
   'home_age_14': 0.132,
   'home_age_15': 0.062,
   'home_age_16': 0.077,
   'home_age_10': 0.071,
   'poi_count': 219,
   'poi_change': 12}},
 '10': {'2116874253039705378': {'work_count': 533,
   'work_female': 0.463,
   'work_male': 0.537,
   'work_age_11': 0.172,
   'work_age_12': 0.183,
   'work_age_13': 0.165,
   'work_age_14': 0.133,
   'work_age_15': 0.054,
   'work_age_16': 0.057,
   'work_age_10': 0.237,
   'home_count': 946,
   'home_female': 0.354,
   'home_male': 0.646,
   'home_age_11': 0.229,
   'home_age_12': 0.208,
   'home_age_13': 0.182,
   'home_age_14': 0.096,
   'home_age_15': 0.049,
   'home_age_16': 0.056,
   'home_age_10': 0.165,
   'poi_count': 23,
   'poi_change': 17}},
 '13': {'2116461606040029066': {'work_count': 212,
   'work_female': 0.302,
   'work_male': 0.698,
   'work_age_11': 0.258,
   'work_age_12': 0.192,
   'work_age_13': 0.1,
   'work_age_14': 0.108,
   'work_age_15': 0.083,
   'work_age_16': 0.142,
   'work_age_10': 0.108,
   'home_count': 220,
   'home_female': 0.256,
   'home_male': 0.744,
   'home_age_11': 0.317,
   'home_age_12': 0.254,
   'home_age_13': 0.103,
   'home_age_14': 0.071,
   'home_age_15': 0.048,
   'home_age_16': 0.063,
   'home_age_10': 0.143,
   'poi_count': 13,
   'poi_change': 6}}}

In [7]:
flow_df

,residence,workplace,commuters,residence_list,workplace_list,odpair
1289118,2116364765040025864,2116404001040007381,1,[2116364765040025864],[2116404001040007381],"(2116364765040025864, 2116404001040007381)"
3439074,2116364765040025864,2116560953039756270,1,[2116364765040025864],[2116560953039756270],"(2116364765040025864, 2116560953039756270)"
7940699,2116364765040025864,2116400988039979704,1,[2116364765040025864],[2116400988039979704],"(2116364765040025864, 2116400988039979704)"

In [10]:
historyflow

,odpair,commuters,residence,workplace
1774138,"(2116364765040025864, 2116364765040025864)",1769,2116364765040025864,2116364765040025864
1774142,"(2116364765040025864, 2116366904040016742)",826,2116364765040025864,2116366904040016742
1774166,"(2116364765040025864, 2116371347040006002)",103,2116364765040025864,2116371347040006002

In [16]:
#{id: [features(0-1 normalized)]}
oa2features

{'2116465375039999220': [0.0303664123430236,
  0.464,
  0.536,
  0.189,
  0.225,
  0.204,
  0.137,
  0.073,
  0.09,
  0.063,
  0.02558693785712171,
  0.481,
  0.519,
  0.207,
  0.247,
  0.178,
  0.132,
  0.062,
  0.077,
  0.071,
  0.03794604003481288,
  0.3723564954682779,
  0.023715415019762844,
  0.027287319422150885,
  0.03867028493894165,
  0.030235162374020158,
  0.026119402985074626,
  0.09302325581395349,
  0.006329113924050633,
  0.0180623973727422,
  0.0,
  0.00546448087431694,
  0.05958549222797927,
  0.0221606648199446],
 '2116874253039705378': [0.004513468426891126,
  0.463,
  0.537,
  0.172,
  0.183,
  0.165,
  0.133,
  0.054,
  0.057,
  0.237,
  0.003500902981318649,
  0.354,
  0.646,
  0.229,
  0.208,
  0.182,
  0.096,
  0.049,
  0.056,
  0.165,
  0.0038294168842471716,
  0.37613293051359514,
  0.003952569169960474,
  0.0032102728731942215,
  0.0020352781546811396,
  0.004479283314669653,
  0.0037313432835820895,
  0.0,
  0.012658227848101266,
  0.0,
  0.0,
  0.0,
  0.007772020725388601,
  0.0],
 '2116461606040029066': [0.0017952257157615736,
  0.302,
  0.698,
  0.258,
  0.192,
  0.1,
  0.108,
  0.083,
  0.142,
  0.108,
  0.0008141634840275928,
  0.256,
  0.744,
  0.317,
  0.254,
  0.103,
  0.071,
  0.048,
  0.063,
  0.143,
  0.0020887728459530026,
  0.3678247734138973,
  0.0,
  0.0,
  0.0013568521031207597,
  0.0,
  0.0,
  0.046511627906976744,
  0.0,
  0.0,
  0.0,
  0.00546448087431694,
  0.0,
  0.002770083102493075]}

In [19]:
od2flow

{('2116364765040025864', '2116364765040025864'): 1776,
 ('2116364765040025864', '2116366904040016742'): 379,
 ('2116364765040025864', '2116371347040006002'): 40}

In [22]:
# {id: [lon, lat]}
oa2centroid

{'2116486832040015748': [116.48565837430807, 40.0169449378472],
 '2116437808040053245': [116.43780807345874, 40.053245122453106],
 '2116524535040022856': [116.52453546914028, 40.022856306257786]}

In [2]:
# [id: [treatment]], treatment is the normalized POI change vector. 
treatment_dict

{'2116465375039999220': [0.6746031746031746,
  0.4968944099378882,
  0.6697936210131332,
  0.495114006514658,
  0.22695035460992907,
  0.1951219512195122,
  0.6875,
  0.7168141592920354,
  0.11333333333333333,
  0.6413043478260869,
  0.675,
  0.37012987012987014],
 '2116874253039705378': [0.6865079365079365,
  0.5217391304347826,
  0.6848030018761726,
  0.46905537459283386,
  0.20567375886524822,
  0.34146341463414637,
  0.6666666666666666,
  0.7404129793510325,
  0.11333333333333333,
  0.6521739130434783,
  0.6125,
  0.37012987012987014],
 '2116461606040029066': [0.6785714285714286,
  0.515527950310559,
  0.6716697936210131,
  0.4723127035830619,
  0.20567375886524822,
  0.3170731707317073,
  0.6666666666666666,
  0.7404129793510325,
  0.11333333333333333,
  0.6521739130434783,
  0.65,
  0.37012987012987014]}

In [28]:
# id of train origin samples, id of test origin samples, 
train_data, test_data

(['2116486832040015748', '2116437808040053245', '2116524535040022856'],
 ['2116643069039794890', '2116651581039847840', '2116773911039683182'])